-- MEMBER DAO 구성하기

-- 1. 로그인 중복체크
SELECT * FROM MEMBER WHERE mID='aaa';

-- 2. DTO 정보 mid로 가져오기
SELECT * FROM MEMBER WHERE mID='aaa';

-- 3. 로그인
SELECT * FROM MEMBER WHERE mID='aaa' AND mPW='1234';

-- 4. 회원가입
INSERT INTO MEMBER(mID, mPW, mNAME, mBIRTH, mGENDER, MBTI)
    VALUES('aaa1', '1234', '홍길동1', '1995-12-05', 'f', 1);
                    
-- 5. 리스트 조회
SELECT MBTINAME, mGENDER, mNAME, LEVELNAME, mWRITECOUNT, mLIKE
    FROM MEMBER M, MEMBER_LEVEL L, MBTI T 
    WHERE M.LEVELNO=L.levelno AND M.MBTI=T.MBTI
    ORDER BY M.LEVELNO DESC, mLIKE DESC;

SELECT *
    FROM (SELECT ROWNUM RN, A.*
        FROM(SELECT MBTINAME, mGENDER, mNAME, LEVELNAME, mWRITECOUNT, mLIKE
                FROM MEMBER M, MEMBER_LEVEL L, MBTI T 
                WHERE M.LEVELNO=L.LEVELNO AND M.MBTI=T.MBTI
                ORDER BY M.LEVELNO DESC, mLIKE DESC) A)
    WHERE RN BETWEEN 1 AND 5;
    
    
-- 6. 회원정보수정
UPDATE MEMBER SET mPW='1234',
                  mNAME='111',
                  mBIRTH='1995-12-12',
                  mGENDER='f',
                  MBTI='1'
        WHERE mID='aaa';


-- 7. 등록된 회원 수
SELECT COUNT(*) FROM MEMBER;

-- 8. 좋아요 올리기
UPDATE MEMBER SET mLIKE = mLIKE+1 WHERE mID='ccc';

-- 9. 글쓴 갯수 올리기
UPDATE MEMBER SET mWRITECOUNT = mWRITECOUNT+1 WHERE mID='aaa';

-- 10. 등급 올리기
UPDATE MEMBER SET LEVELNO = 3 WHERE mWRITECOUNT>=100;

-- 11. 멤버 검색
SELECT *
    FROM (SELECT ROWNUM RN, A.*
        FROM(SELECT MBTINAME, mGENDER, mNAME, LEVELNAME, mWRITECOUNT, mLIKE
                FROM MEMBER M, MEMBER_LEVEL L, MBTI T 
                WHERE M.LEVELNO=L.LEVELNO AND M.MBTI=T.MBTI
                ORDER BY M.LEVELNO DESC, mLIKE DESC) A)
    WHERE mNAME LIKE '%'||'홍'||'%' AND RN BETWEEN 1 AND 5;

-- 12. 회원 상세보기(조회수 올리기 포함한)
SELECT M.*, LEVELNAME, MBTINAME
    FROM MEMBER M, MEMBER_LEVEL L, MBTI T
    WHERE M.LEVELNO=L.LEVELNO AND M.MBTI=T.MBTI AND M.mID='aaa';


SELECT * FROM MEMBER;
COMMIT;




-- FREEBOARD DAO 구성하기

-- 1. 글목록
SELECT B.*, M.mNAME
    FROM FREEBOARD B, MEMBER M
    WHERE B.mID=M.mID
    ORDER BY bGROUP DESC, bSTEP;

SELECT *
    FROM (SELECT ROWNUM RN, A.*
        FROM(SELECT B.*, M.mNAME
                FROM FREEBOARD B, MEMBER M
                WHERE B.mID=M.mID
                ORDER BY bGROUP DESC, bSTEP) A)
    WHERE RN BETWEEN 2 AND 3 AND bDELETEMARK=0;

-- 2. 등록된 글 수
SELECT COUNT(*) FROM FREEBOARD WHERE bDELETEMARK=0;

-- 3. 원글쓰기
SELECT MBTI FROM MBTI WHERE MBTINAME='INTJ';

INSERT INTO FREEBOARD(bNO, mID, MBTI, bTITLE, bCONTENT, bFILENAME,
                bGROUP, bSTEP, bINDENT, bIP)
        VALUES(FREEBOARD_SEQ.NEXTVAL, 'aaa', (SELECT MBTI FROM MBTI WHERE MBTINAME='INTJ'), 'title', 'content', 'filename',
                FREEBOARD_SEQ.CURRVAL, 0, 0, '123.123.123.123');

-- 4. 답변글 쓰기전 스텝
UPDATE FREEBOARD SET bSTEP = bSTEP+1 WHERE bGROUP=5 AND bSTEP>0;

-- 5. 답변글 쓰기
SELECT M.MBTI FROM MEMBER M, MBTI T WHERE M.MBTI=T.MBTI AND mID='aaa';

INSERT INTO FREEBOARD(bNO, mID, MBTI, bTITLE, bCONTENT, bFILENAME,
                bGROUP, bSTEP, bINDENT, bIP)
        VALUES(FREEBOARD_SEQ.NEXTVAL, 'aaa',
            (SELECT M.MBTI FROM MEMBER M, MBTI T WHERE M.MBTI=T.MBTI AND mID='aaa'),
            '글1-1', 'content', 'filename', 5, 1, 1, '123.123.123.123');

SELECT * FROM FREEBOARD;
SELECT * FROM MEMBER;
-- 6-1. 글 상세보기
SELECT *  FROM FREEBOARD WHERE bNO=1;

SELECT MBTINAME, B.*, M.mNAME, LEVELNAME
        FROM FREEBOARD B, MEMBER M, MBTI T, MEMBER_LEVEL L
        WHERE B.mID=M.mID AND B.MBTI=T.MBTI AND bNO=1 AND M.LEVELNO=L.LEVELNO;

-- 6-2. 답변들 상세보기
SELECT MBTINAME, B.*, M.mNAME, LEVELNAME
        FROM FREEBOARD B, MEMBER M, MBTI T, MEMBER_LEVEL L
        WHERE B.mID=M.mID AND B.MBTI=T.MBTI AND bGROUP=1 AND bNO!=1 AND M.LEVELNO=L.LEVELNO;
        
-- 7. 조회수 올리기
UPDATE FREEBOARD SET bHIT = bHIT+1 WHERE bNO=1;

-- 8. 좋아요 올리기
UPDATE FREEBOARD SET bLIKE = bLIKE+1 WHERE bNO=1;

-- 9. 글 수정하기
UPDATE FREEBOARD SET MBTI='5',
                    bTITLE='수정 제목',
                    bCONTENT='수정 본문',
                    bFILENAME=NULL,
                    bIP='123.123.123.111'
            WHERE bNO=2;

-- 10. 글 삭제하기
UPDATE FREEBOARD SET bDELETEMARK = 1 WHERE bNO=5;

SELECT * FROM FREEBOARD;


-- 11. 댓글 갯수표현하기













