--MEMBER, MEMBER_LEVEL, MEMBER_MNO_SQ 테이블
--오타로 인한 칼럼명 변경
ALTER TABLE MEMBER_LEVEL RENAME COLUMN LEVLENAME TO LEVELNAME;

DROP TABLE MEMBER_LEVEL;
DROP TABLE MEMBER;
DROP SEQUENCE MEMBER_MNO_SQ;


CREATE TABLE MEMBER_LEVEL(
    LEVELNO NUMBER(2) PRIMARY KEY,
    LEVELNAME VARCHAR2(20) NOT NULL);

CREATE SEQUENCE MEMBER_MNO_SQ
    START WITH 1
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 9999
    NOCACHE
    NOCYCLE;
    
CREATE TABLE MEMBER(
    MNO NUMBER(4) PRIMARY KEY,
    MNAME VARCHAR2(30) NOT NULL,
    MPW VARCHAR2(30) CHECK(LENGTH(MPW)<=8),
    MEMAIL VARCHAR2(30) UNIQUE,
    MPOINT NUMBER(8) CHECK(MPOINT>=0),
    MRDATE DATE DEFAULT SYSDATE,
    LEVELNO NUMBER(2) REFERENCES MEMBER_LEVEL(LEVELNO));

INSERT INTO MEMBER_LEVEL VALUES (-1, 'BLACK');
INSERT INTO MEMBER_LEVEL VALUES (0, '일반');
INSERT INTO MEMBER_LEVEL VALUES (1, '실버');
INSERT INTO MEMBER_LEVEL VALUES (2, '골드');
SELECT * FROM MEMBER_LEVEL;

INSERT INTO MEMBER VALUES(MEMBER_MNO_SQ.NEXTVAL,'홍길동','aa','hong@hong.com',0,'22/03/10',0);
INSERT INTO MEMBER VALUES(MEMBER_MNO_SQ.NEXTVAL,'신길동','bb','sin@sin.com',1000,'22/04/15',1);
SELECT*FROM MEMBER;

SELECT MNO, MNAME, MRDATE, MEMAIL, MPOINT, CONCAT(LEVELNAME, '고객')
    FROM MEMBER M, MEMBER_LEVEL L
    WHERE M.LEVELNO=L.LEVELNO;