-- [IV] 쇼핑몰 설계


-- 고객 테이블 생성(1번 테이블)
DROP TABLE CUSTOMER;
CREATE TABLE CUSTOMER (
    MID VARCHAR2(30) PRIMARY KEY,
    MNAME VARCHAR2(30) NOT NULL,
    MADDR VARCHAR2(300) NOT NULL,
    MTEL VARCHAR2(30) NOT NULL UNIQUE,
    MEMAIL VARCHAR2(100));
SELECT * FROM CUSTOMER;
DELETE FROM CUSTOMER WHERE MID='QQA';

INSERT INTO CUSTOMER VALUES('abc','홍길동','서울 강남구','010-1111-1111',NULL);
INSERT INTO CUSTOMER VALUES('DEF','전투황','서울 서대문구','010-3333-3333',NULL);

-- 상품 테이블 생성(2번 테이블)
DROP TABLE PRODUCT;
CREATE TABLE PRODUCT (
    PCODE VARCHAR(30) PRIMARY KEY,
    PNAME VARCHAR2(50) NOT NULL,
    PPRICE NUMBER(8) NOT NULL,
    PSTOCK NUMBER(5) NOT NULL);
SELECT * FROM PRODUCT;

INSERT INTO PRODUCT VALUES('A1','맥주',3000,20);
INSERT INTO PRODUCT VALUES('B1','땡콩',3500,10);
INSERT INTO PRODUCT VALUES('A2','쇠주',2000,30);
INSERT INTO PRODUCT VALUES('B2','오징어',5000,5);
INSERT INTO PRODUCT VALUES('c1','기저귀',7000,10);

-- 장바구니 테이블 생성 및 시퀀스 생성(3번 테이블)
DROP SEQUENCE CART_SQ;
CREATE SEQUENCE CART_SQ
    NOCACHE
    NOCYCLE;
DROP TABLE CART;
CREATE TABLE CART (
    CNO NUMBER(20) PRIMARY KEY,
    MID VARCHAR2(30) REFERENCES CUSTOMER(MID),
    PCODE VARCHAR2(30) REFERENCES PRODUCT(PCODE),
    CQTY NUMBER(5) CHECK(CQTY>=0),
    CCOST NUMBER(8) CHECK(CCOST>=0));
SELECT * FROM CART;

-- 주문 테이블 생성(4번 테이블)
DROP TABLE ORDERS;
CREATE TABLE ORDERS (
    ONO NUMBER(20) PRIMARY KEY,
    MID VARCHAR(30) REFERENCES CUSTOMER(MID),
    OADDR VARCHAR(30) NOT NULL,
    OTEL VARCHAR2(30) NOT NULL,
    ODATE DATE DEFAULT SYSDATE);
SELECT * FROM ORDERS;

INSERT INTO ORDERS(ONO, MID, OADDR, OTEL) VALUES(CONCAT(TO_CHAR(SYSDATE, 'RRMMDD'), LPAD(TO_CHAR(CART_SQ.NEXTVAL),5,'0')), 'abc', '서울 강남구', '010-1111-1111');
INSERT INTO ORDERS(ONO, MID, OADDR, OTEL) VALUES(CONCAT(TO_CHAR(SYSDATE, 'RRMMDD'), LPAD(TO_CHAR(CART_SQ.NEXTVAL),5,'0')), 'DEF', '서울 서대문구', '010-2222-2222');
INSERT INTO ORDERS(ONO, MID, OADDR, OTEL) VALUES(CONCAT(TO_CHAR(SYSDATE, 'RRMMDD'), LPAD(TO_CHAR(CART_SQ.NEXTVAL),5,'0')), 'abc', '경기도 과천', '010-3333-3333');

-- 주문상세 테이블 만들기(5번 테이블)
DROP TABLE DT_OR;
CREATE TABLE DT_OR (
    ONO NUMBER(8) REFERENCES ORDERS(ONO),
    PCODE VARCHAR(30) REFERENCES PRODUCT(PCODE),
    OQTY NUMBER(5) CHECK(OQTY>=0),
    OCOSTS NUMBER(8) CHECK(OCOSTS>=0));
SELECT * FROM DT_OR;
VALUES ('2204190001','A1',3,3*(SELECT PPRICE FROM PRODUCT WHERE PCODE = 'A1')
SELECT ONO, PCODE, OQTY, OCOSTS
    FROM ORDERS, PRODUCT