create database fourman character set=utf8;
commit;

USE fourman;

CREATE TABLE TEST(
NAME CHAR(30)
);

-- Admin
DROP SEQUENCE ADMIN_SQ;
DROP TABLE ADMIN_L;
DROP TABLE ADMIN;

CREATE TABLE ADMIN(
    aNO int(2) PRIMARY KEY,
    aID VARCHAR(50) UNIQUE NOT NULL,
    aPW VARCHAR(50) NOT NULL,
    aEMAIL VARCHAR(50) NOT NULL,
    aNAME VARCHAR(50) NOT NULL,
    aTEL VARCHAR(50) NOT NULL,
    aLEVEL VARCHAR(50) DEFAULT 0 REFERENCES ADMIN_L(aLEVEL),
    aRDATE DATE DEFAULT SYSDATE
);

-- ADMIN LEVEL
CREATE TABLE ADMIN_L(
    aLEVEL VARCHAR(10) PRIMARY KEY,
    aLEVEL_NAME VARCHAR(50)
);

CREATE SEQUENCE ADMIN_SQ
INCREMENT BY 1
MAXVALUE 99 NOCACHE NOCYCLE;

-- ADMIN LELVE DATA
INSERT INTO ADMIN_L VALUES(0, 'MANAGER');
INSERT INTO ADMIN_L VALUES(1, 'HEAD_MANAGER');
INSERT INTO ADMIN_L VALUES(2, 'MASTER');

SELECT * FROM ADMIN;
SELECT * FROM ADMIN_L;



-- 시퀀스 연습해보기
CREATE TABLE SEQUENCES(
	NAME VARCHAR(32),
    CURRVAL BIGINT UNSIGNED
)
ENGINE = InnoDB

DELIMITER $$
	CREATE PROCEDURE 'create_sequence' (IN the_name text)
    MODIFIES SQL DATA
    DETERMINISTIC
    BEGIN
		DELETE FROM sequences WHERE name = the_name;
        INSERT INTO sequences VALUES(the_name, 0);
	END

DELIMITER $$
	CREATE FUNCTION 'nextval' (the_nmae VARCHAR(32))
    RETURNS BIGINT UNSIGNED



DROP FUNCTION IF EXISTS get_seq;

DELIMITER $$
CREATE FUNCTION get_seq(p_seq_name VARCHAR(45))
RETURNS INT READS SQL DATA
BEGIN
DECLARE RESULT_ID INT;
UPDATE seq_mysql SET id = LIST_INSET_ID(id+1)
WHERE ano = p_seq_name;
SET RESULT_ID = (SELECT LAST_INSET_ID());
RETURN RESULT_ID;
END $$
DELIMITER ;

INSERT INTO seq_mysql
VALUES (0, 'adminno');

CALL create_sequence('Test');
get_seq('adminno');


CREATE TABLE ADMIN(
    aNO int(2) PRIMARY KEY,
    aID VARCHAR(50) UNIQUE NOT NULL,
    aPW VARCHAR(50) NOT NULL,
    aEMAIL VARCHAR(50) NOT NULL,
    aNAME VARCHAR(50) NOT NULL,
    aTEL VARCHAR(50) NOT NULL,
    aLEVEL VARCHAR(50) DEFAULT 0
);

INSERT INTO ADMIN
	VALUES((SELECT get_seq('adminno') FROM DUAL), 'aaa', '1234', 'moan12@naver.com', '홍길동', '010-2222-3333', '김');
	
DROP TABLE ADMIN;



