-- 1. EXERD 작성 후,
-- 2. 테이블을 삭제하고 테이블을 생성하시오

-- 삭제
DROP TABLE CUS_LEVEL;
DROP TABLE CUSTOMER;

DROP SEQUENCE CUSTOMER_SQ; -- 시퀀스 삭제 필요할 경우

-- 생성
CREATE TABLE CUS_LEVEL (
    LEVELNO NUMBER(2) PRIMARY KEY,
    LEVENAME VARCHAR2(20) NOT NULL);
    
CREATE TABLE CUSTOMER (
    CNO NUMBER(6) PRIMARY KEY,
    CNAME VARCHAR2(30) NOT NULL,
    JOINDATE DATE DEFAULT SYSDATE,
    PHONE VARCHAR2(30) UNIQUE,
    POINT NUMBER(8),
    LEVELNO NUMBER(2) REFERENCES CUS_LEVEL(LEVELNO));

CREATE SEQUENCE CUSTOMER_SQ NOCACHE NOCYCLE;

-- 테이블 네임 오타로 인한 수정 진행
ALTER TABLE CUSTOMER RENAME COLUMN PHNOE TO PHONE;



-- 데이터 입력
INSERT INTO CUS_LEVEL VALUES (1, 'VVIP');
INSERT INTO CUS_LEVEL VALUES (2, 'VIP');
INSERT INTO CUS_LEVEL VALUES (3, 'VORMAL');
INSERT INTO CUS_LEVEL VALUES (4, 'BLACK');
SELECT * FROM CUS_LEVEL;

INSERT INTO CUSTOMER VALUES (CUSTOMER_SQ.NEXTVAL, '홍길동', '2022/03/10', '010-9999-9999', 0, 1);
INSERT INTO CUSTOMER VALUES (CUSTOMER_SQ.NEXTVAL, '이철수', '2022/04/19', '010-8888-8888', NULL, 2);
SELECT * FROM CUSTOMER;

-- 출력
SELECT CNO, CNAME, JOINDATE, PHONE, POINT, LEVELNAME
    FROM CUSTOMER C, CUS_LEVEL CL 
    WHERE C.LEVELNO=CL.LEVELNO;





