-- DROP 
DROP SEQUENCE BOOK_SEQ;
DROP TABLE BOOK;

-- CREATE
CREATE SEQUENCE BOOK_SEQ
    MAXVALUE 99999
    NOCACHE
    NOCYCLE;

CREATE TABLE BOOK (
    bID NUMBER(5) PRIMARY KEY, -- 책번호
    bTITLE VARCHAR2(30) NOT NULL, -- 책제목
    bPRICE NUMBER(7) NOT NULL, -- 책가격
    bIMAGE1 VARCHAR2(30) NOT NULL, -- 책 대표 이미지(첨부 안할 경우 : noimg.png로 대체)
    bIMAGE2 VARCHAR2(30) NOT NULL, -- 책 부가 이미지(첨부 안할 경우 : NOTHING.JSP로 대체)
    bCONTENT VARCHAR2(4000),        -- 책 설명(1333글자 이내)
    bDISCOUNT NUMBER(3) NOT NULL,   -- 할인율(0~100)
    bRDATE DATE DEFAULT SYSDATE     -- 책 등록일
);

SELECT * FROM BOOK;

-- 책등록(INSERT)
INSERT INTO BOOK (bID, bTITLE, bPRICE, bIMAGE1, bIMAGE2, bCONTENT, bDISCOUNT)
    VALUES (BOOK_SEQ.NEXTVAL, '자바의 정석', 30000, 'noimg.png', 'NOTHING.JPG', '책설명', 20);
INSERT INTO BOOK (bID, bTITLE, bPRICE, bIMAGE1, bIMAGE2, bCONTENT, bDISCOUNT)
    VALUES (BOOK_SEQ.NEXTVAL, '그림 알고리즘', 23000, 'NOTHING.JPG', 'noimg.png', '책설명', 20);
INSERT INTO BOOK (bID, bTITLE, bPRICE, bIMAGE1, bIMAGE2, bCONTENT, bDISCOUNT)
    VALUES (BOOK_SEQ.NEXTVAL, '패턴의 모든 것', 35000, 'noimg.png', 'NOTHING.JPG', '책설명', 20);
INSERT INTO BOOK (bID, bTITLE, bPRICE, bIMAGE1, bIMAGE2, bCONTENT, bDISCOUNT)
    VALUES (BOOK_SEQ.NEXTVAL, '데이터베이스 관리', 18000, 'NOTHING.JPG', 'noimg.png', '책설명', 20);

UPDATE BOOK SET bIMAGE1='NOTHING.JPG' WHERE bID IN (2,4);
-- 책목록(전체list) 신간 도서 순으로 출력
SELECT * FROM BOOK ORDER BY bRDATE DESC;

-- 책목록(top-N구문)
SELECT *
    FROM (SELECT ROWNUM RN, A.* FROM (SELECT * FROM BOOK ORDER BY bRDATE DESC) A)
    WHERE  RN BETWEEN 2 AND 3;

-- 등록된 책 갯수
SELECT COUNT(*) CNT FROM BOOK;

-- 책 상세보기(bID로 dto가져오기)
SELECT * FROM BOOK WHERE BID=1;

COMMIT;
