-- 테이블 & 시퀀스 DROP 및 CREATE
DROP TABLE CUSTOMER;
CREATE TABLE CUSTOMER(
    cID VARCHAR2(50) PRIMARY KEY,
    cPW VARCHAR2(50) NOT NULL,
    cNAME VARCHAR2(50) NOT NULL,
    cTEL VARCHAR2(50) NOT NULL,
    cEMAIL VARCHAR2(50),
    cADDRESS VARCHAR2(250),
    cGENDER VARCHAR2(10) NOT NULL,
    cBIRTH DATE NOT NULL,
    cRDATE DATE DEFAULT SYSDATE
);

SELECT * FROM CUSTOMER;

-- DROP
DROP SEQUENCE BOOK_SEQ;
DROP TABLE BOOK;

-- CREATE
CREATE SEQUENCE BOOK_SEQ
    MAXVALUE 99999
    NOCACHE
    NOCYCLE;

CREATE TABLE BOOK (
    bID NUMBER(5) PRIMARY KEY, -- 책번호
    bTITLE VARCHAR2(30) NOT NULL, -- 책제목
    bPRICE NUMBER(7) NOT NULL, -- 책가격
    bIMAGE1 VARCHAR2(30) NOT NULL, -- 책 대표 이미지(첨부 안할 경우 : noimg.png로 대체)
    bIMAGE2 VARCHAR2(30) NOT NULL, -- 책 부가 이미지(첨부 안할 경우 : NOTHING.JSP로 대체)
    bCONTENT VARCHAR2(4000),        -- 책 설명(1333글자 이내)
    bDISCOUNT NUMBER(3) NOT NULL,   -- 할인율(0~100)
    bRDATE DATE DEFAULT SYSDATE     -- 책 등록일
);

SELECT * FROM TAB;



--DROP
DROP SEQUENCE FILEBOARD_SEQ;
DROP TABLE FILEBOARD;

--CREATE
CREATE SEQUENCE FILEBOARD_SEQ
MAXVALUE 999999
NOCACHE
NOCYCLE;

CREATE TABLE FILEBOARD(
    fNUM NUMBER(7) PRIMARY KEY, -- 글번호
    cID VARCHAR2(50) REFERENCES CUSTOMER(CID), -- 작성자(cID)
    fSUBJECT VARCHAR2(250) NOT NULL, -- 글 제목
    fCONTENT VARCHAR2(4000), -- 본문
    fFILENAME VARCHAR2(50), -- 첨부파일명
    fPW VARCHAR2(50) NOT NULL, -- 비번
    fHIT NUMBER(7) DEFAULT 0 NOT NULL, -- 조회수
    fREF NUMBER(7) NOT NULL, -- 글 그룹
    fRE_STEP NUMBER(7) NOT NULL, -- 그룹 내 출력순서
    fRE_LEVEL NUMBER(7) NOT NULL, -- 들여쓰기 정도
    fIP VARCHAR2(50) NOT NULL, -- 글쓴 컴퓨터 IP
    fRDATE DATE DEFAULT SYSDATE NOT NULL -- 글 등록 시점
);
SELECT * FROM FILEBOARD;

SELECT * FROM TAB;
