DROP TABLE STUDENT;
DROP TABLE MAJOR;
DROP SEQUENCE MAJOR_SQ;
DROP SEQUENCE STUDENT_SQ;

CREATE TABLE MAJOR(
    mNO NUMBER(2) PRIMARY KEY,
    mNAME VARCHAR2(50)
);

CREATE TABLE STUDENT (
    sNO NUMBER(7) PRIMARY KEY,
    mNO NUMBER(2) REFERENCES MAJOR(mNO),
    sNAME VARCHAR2(50),
    SCORE NUMBER(3) CHECK(0<=SCORE AND SCORE<=100),
    sEXPEL NUMBER(1) DEFAULT 0
);

CREATE SEQUENCE MAJOR_SQ
MAXVALUE 9999
NOCACHE NOCYCLE;

CREATE SEQUENCE STUDENT_SQ
MAXVALUE 9999
NOCACHE NOCYCLE;

SELECT * FROM MAJOR;
SELECT * FROM STUDENT;


INSERT INTO MAJOR VALUES(MAJOR_SQ.NEXTVAL, '빅데이터학');
INSERT INTO MAJOR VALUES(MAJOR_SQ.NEXTVAL, '경영정보학');
INSERT INTO MAJOR VALUES(MAJOR_SQ.NEXTVAL, '컴퓨터공학');
INSERT INTO MAJOR VALUES(MAJOR_SQ.NEXTVAL, '산업공학');
INSERT INTO MAJOR VALUES(MAJOR_SQ.NEXTVAL, '인공지능학');

    sNO NUMBER(7) PRIMARY KEY,
    mNO NUMBER(2) REFERENCES MAJOR(mNO),
    sNAME VARCHAR2(50),
    SCORE NUMBER(3) CHECK(0<=SCORE AND SCORE<=100),
    sEXPEL NUMBER(1)
    
INSERT INTO STUDENT VALUES(TO_CHAR(SYSDATE, 'YYYY')||LPAD(STUDENT_SQ.NEXTVAL, 3, 0), 1, '정우성', 90, 0);
INSERT INTO STUDENT VALUES(TO_CHAR(SYSDATE, 'YYYY')||LPAD(STUDENT_SQ.NEXTVAL, 3, 0), 1, '박세영', 80, 0);
INSERT INTO STUDENT VALUES(TO_CHAR(SYSDATE, 'YYYY')||LPAD(STUDENT_SQ.NEXTVAL, 3, 0), 3, '배수지', 100, 0);
INSERT INTO STUDENT VALUES(TO_CHAR(SYSDATE, 'YYYY')||LPAD(STUDENT_SQ.NEXTVAL, 3, 0), 2, '아이유', 100, 0);
INSERT INTO STUDENT VALUES(TO_CHAR(SYSDATE, 'YYYY')||LPAD(STUDENT_SQ.NEXTVAL, 3, 0), 4, '제시카', 50, 0);
INSERT INTO STUDENT VALUES(TO_CHAR(SYSDATE, 'YYYY')||LPAD(STUDENT_SQ.NEXTVAL, 3, 0), 5, '박효신', 15, 0);
INSERT INTO STUDENT VALUES(TO_CHAR(SYSDATE, 'YYYY')||LPAD(STUDENT_SQ.NEXTVAL, 3, 0), 5, '김태리', 99, 0);
INSERT INTO STUDENT VALUES(TO_CHAR(SYSDATE, 'YYYY')||LPAD(STUDENT_SQ.NEXTVAL, 3, 0), 3, '정은지', 79, 0);
INSERT INTO STUDENT VALUES(TO_CHAR(SYSDATE, 'YYYY')||LPAD(STUDENT_SQ.NEXTVAL, 3, 0), 3, '김떡순', 85, 0);
INSERT INTO STUDENT VALUES(TO_CHAR(SYSDATE, 'YYYY')||LPAD(STUDENT_SQ.NEXTVAL, 3, 0), 3, '김제적', 15, 1);
INSERT INTO STUDENT VALUES(TO_CHAR(SYSDATE, 'YYYY')||LPAD(STUDENT_SQ.NEXTVAL, 3, 0), 5, '또제적', 5, 1);


--학번검색쿼리
SELECT SNO, SNAME, MNAME, SCORE FROM STUDENT S, MAJOR M WHERE S.MNO=M.MNO AND SNO='2022002';


--이름검색쿼리
SELECT SNO, SNAME, MNAME, SCORE FROM STUDENT S, MAJOR M WHERE S.MNO=M.MNO AND SNAME='아이유';

--전공검색쿼리
SELECT ROWNUM RANK, SNAME, MNAME, SCORE
    FROM (SELECT SNAME||'('||SNO||')' "SNAME", MNAME||'('||S.MNO||')' "MNAME", SCORE
    FROM STUDENT S, MAJOR M WHERE S.MNO=M.MNO AND MNAME='컴퓨터공학' ORDER BY SCORE DESC) A;

--학생입력쿼리
INSERT INTO STUDENT (SNO, MNO, SNAME, SCORE)
    VALUES(TO_CHAR(SYSDATE, 'YYYY')||LPAD(STUDENT_SQ.NEXTVAL, 3, 0), (SELECT MNO FROM MAJOR WHERE MNAME='컴퓨터공학'), '음치킨', 95);
select * from student;
delete from student where mno is null;
commit;
--학생수정쿼리
UPDATE STUDENT SET MNO=(SELECT MNO FROM MAJOR WHERE MNAME='경영정보학'), SNAME='홍차차', SCORE=10 WHERE SNO=2022011;

--학생출력쿼리
SELECT ROWNUM RANK, SNAME, MNAME, SCORE
    FROM (SELECT SNAME||'('||SNO||')' "SNAME", MNAME||'('||S.MNO||')' "MNAME", SCORE
    FROM STUDENT S, MAJOR M WHERE S.MNO=M.MNO ORDER BY SCORE DESC) A;
    
--제적자출력
SELECT ROWNUM RANK, SNAME, MNAME, SCORE
    FROM (SELECT SNAME||'('||SNO||')' "SNAME", MNAME||'('||S.MNO||')' "MNAME", SCORE
    FROM STUDENT S, MAJOR M WHERE S.MNO=M.MNO AND SEXPEL=1 ORDER BY SCORE DESC) A;

--제적처리
UPDATE STUDENT SET SEXPEL=1 WHERE SNO=2022006;
commit;
select * from student;