-- 테이블 생성, 시퀀스(같은 이름의 테이블이 생성되었을 경우 DROP)
DROP TABLE PERSON;
DROP TABLE JOB;
DROP SEQUENCE PERSON_SQ;

CREATE TABLE JOB (
    JNO NUMBER(2) PRIMARY KEY,
    JNAME VARCHAR2(30) NOT NULL
    );
SELECT * FROM JOB;

CREATE TABLE PERSON (
    PNO NUMBER(5) PRIMARY KEY ,
    PNAME VARCHAR2(30) NOT NULL,
    JNO NUMBER(2) REFERENCES JOB(JNO),
    KOR NUMBER(3),
    ENG NUMBER(3),
    MAT NUMBER(3)
    );
SELECT * FROM PERSON;

CREATE SEQUENCE PERSON_SQ NOCACHE NOCYCLE;

-- 더미데이터(JOB -> PERSON 순서대로. PARENT TABLE먼저)
INSERT INTO JOB VALUES (10, '배우');
INSERT INTO JOB VALUES (20, '가수');

INSERT INTO PERSON VALUES (PERSON_SQ.NEXTVAL, '정우성', 10, 90, 80, 81);
INSERT INTO PERSON VALUES (PERSON_SQ.NEXTVAL, '박세영', 10, 80, 90, 80);
INSERT INTO PERSON VALUES (PERSON_SQ.NEXTVAL, '배수지', 20, 20, 90, 90);
INSERT INTO PERSON VALUES (PERSON_SQ.NEXTVAL, '설현', 20, 95, 95, 95);
INSERT INTO PERSON VALUES (PERSON_SQ.NEXTVAL, '송혜교', 10, 100, 100, 100);


-- 필요한 쿼리문(사용자 선택옵션)
-- 1번 : PNAME, JNAME, KOR, ENG, MAT을 입력받아 INSERT
INSERT INTO PERSON VALUES (PERSON_SQ.NEXTVAL, '홍길동', (SELECT JNO FROM JOB WHERE JNAME='배우'), 50, 50, 50);
COMMIT;

-- 2번 : 직업명을 입력받아 등수, 이름(PNO), 직업명 및
-- 국어(KOR), 영어(ENG), 수학(MAT) 총점을 출력(총점기준으로 내림차순 정렬)
SELECT ROWNUM RANK, A.*
    FROM (SELECT PNAME, JNAME , KOR, ENG, MAT, KOR+ENG+MAT SUM
        FROM PERSON P, JOB J
        WHERE P.JNO=J.JNO AND JNAME='배우'
        ORDER BY SUM DESC) A;
    
-- 3번 : 모든 행의 등수, 이름(PNO), 직업명, 국어(KOR), 영어(ENG), 수학(MAT), 총점을 출력
SELECT ROWNUM RANK, A.*
    FROM (SELECT PNAME, JNAME , KOR, ENG, MAT, KOR+ENG+MAT SUM
        FROM PERSON P, JOB J
        WHERE P.JNO=J.JNO
        ORDER BY SUM DESC) A;




