-- SEQUENCE & TABLE DROP/TABLE
DROP TABLE BOOK CASCADE CONSTRAINTS;
DROP TABLE MEMBER CASCADE CONSTRAINTS;
DROP SEQUENCE BOOK_SQ;

CREATE TABLE MEMBER(
    mID VARCHAR2(100) PRIMARY KEY,
    mPW VARCHAR2(100) NOT NULL,
    mNAME VARCHAR2(100) NOT NULL,
    mMAIL VARCHAR2(100) NOT NULL,
    mPOST VARCHAR2(100), -- 우편번호
    mADDR VARCHAR2(100) -- 주소
);

CREATE SEQUENCE BOOK_SQ MAXVALUE 99999999 NOCYCLE NOCACHE;

CREATE TABLE BOOK(
    bNUM NUMBER(8) PRIMARY KEY,
    bTITLE VARCHAR2(100) NOT NULL,
    bWRITER VARCHAR2(100) NOT NULL,
    bRDATE DATE DEFAULT SYSDATE NOT NULL, -- 출판일
    bIMG1 VARCHAR2(1000) DEFAULT 'noImg.png' NOT NULL,
    bIMG2 VARCHAR2(1000) DEFAULT 'noImg.png' NOT NULL,
    bINFO VARCHAR2(4000)
);


-- DUMMY DATA INSERT
INSERT INTO MEMBER VALUES('aaa','1234','홍길동','hong@naver.com','12345','서울');
INSERT INTO BOOK VALUES(BOOK_SQ.NEXTVAL, 'spring', '노홍철', SYSDATE, 'noImg.png', 'noImg.png', 'spring basic');

INSERT INTO BOOK (bNUM, bTITLE, bWRITER, bRDATE, bIMG1, bINFO)
    VALUES(BOOK_SQ.NEXTVAL, 'jsp', '정형돈', SYSDATE, 'noImg.png', 'jsp basic');

INSERT INTO BOOK (bNUM, bTITLE, bWRITER, bRDATE, bIMG1, bINFO)
    VALUES(BOOK_SQ.NEXTVAL, 'JAVA', '박명수', SYSDATE, 'noImg.png', 'JAVA basic');

INSERT INTO BOOK (bNUM, bTITLE, bWRITER, bIMG1, bINFO)
    VALUES(BOOK_SQ.NEXTVAL, 'DB', '유재석', 'noImg.png', 'DB basic');













