-- TABLE DROP & CREATE
DROP TABLE FRIENDS CASCADE CONSTRAINTS;
DROP SEQUENCE FRIENDS_SQ;

CREATE TABLE FRIENDS(
    NO NUMBER(6) PRIMARY KEY,
    NAME VARCHAR2(30),
    PHONE VARCHAR2(30)
);
CREATE SEQUENCE FRIENDS_SQ
MAXVALUE 999999
NOCACHE
NOCYCLE;

-- 친구추가
INSERT INTO FRIENDS VALUES (FRIENDS_SQ.NEXTVAL, '홍길동', '010-9999-9999');

-- 전체조회
SELECT * FROM FRIENDS;
COMMIT;

-- 친구검색
SELECT * FROM FRIENDS WHERE NAME LIKE '%'||'길'||'%' AND PHONE LIKE '%'||'9999'||'%';

