-- TABLE DROP & CREATE
DROP TABLE FRIENDS CASCADE CONSTRAINTS;
CREATE TABLE FRIENDS(
    NO NUMBER(6) PRIMARY KEY,
    NAME VARCHAR2(30) NOT NULL,
    PHONE VARCHAR2(30) NOT NULL
);
CREATE SEQUENCE FRIENDS_SQ
MAXVALUE 999999
NOCACHE
NOCYCLE;

-- 친구추가
INSERT INTO FRIENDS VALUES (FRIENDS_SQ.NEXTVAL, '홍길동', '010-9999-9999');

-- 친구조회
SELECT * FROM FRIENDS;



