-- 
INSERT INTO DEPT VALUES(70,'IT','SEOUL');
ROLLBACK;
COMMIT;
SELECT * FROM DEPT;

-- 1. 부서번호 중복체크
SELECT * FROM DEPT WHERE DEPTNO=70; -- rs.next()결과가 true(중복되었습니다)/false(부서명, 부서위치 입력받아 입력)
SELECT COUNT(*) CNT FROM DEPT WHERE DEPTNO=70;
-- 2. 입력
INSERT INTO DEPT VALUES(55,'IT','SEOUL');
UPDATE FROM DEPT WHERE DEPTNO=55;
SELECT * FROM DEPT;
-- 수정
UPDATE DEPT SET DNAME='OPERATIONS', LOC='BOSTON' WHERE DEPTNO=40;
COMMIT;
DELETE FROM DEPT WHERE DEPTNO NOT IN(10,20,30,40);
SELECT * FROM DEPT WHERE DEPTNO=70;